# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Wrench.Dashio
PackageVersion: 0.1.2
InstallerType: inno
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/EverythingSuckz/Dashio/releases/download/v0.1.2/Dashio-Setup-0.1.2-x64.exe
  InstallerSha256: 923E8B8AEDCD4111B1BA91EE386ECBECCFDB4D0A4A88E5FEB8F55206CAA1D359
ManifestType: installer
ManifestVersion: 1.12.0
