# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Wrench.Dashio
PackageVersion: 0.1.2
PackageLocale: en-US
Publisher: Wrench
PackageName: Dashio
License: MIT
Copyright: MIT License, Wrench and Dashio contributors
ShortDescription: A dashboard for Windows 11
ManifestType: defaultLocale
ManifestVersion: 1.12.0
